limit: 3
line: kodo
streamers:
  0SW_txaHaR4.mp4:
    copyright: 1
    cover: 0SW_txaHaR4.jpg
    desc: "\u5B9A\u671F\u5206\u4EABRunningMan \u6C42\u8D5E\u6C42\u4E09\u8FDE"
    desc_format_id: 0
    dolby: 0
    dynamic: ''
    open_subtitle: false
    source: https://www.youtube.com/watch?v=0SW_txaHaR4
    subtitle:
      lan: ''
      open: 0
    tag: "RunningMan,\u91D1\u949F\u56FD,\u5B8B\u667A\u5B5D,\u674E\u5149\u6D19,\u5218\
      \u5728\u77F3,HaHa,\u6881\u4E16\u707F,\u5168\u662D\u65FB"
    tid: 71
    title: "#Running Man\uFF5CRM3\u4F4D\u5927\u54E5 \u8AB0\u662F\u77E5\u8B58\u738B\
      \uFF5C\u7B2C705\u96C6 \uFF5C\u9022\u5468\u4E00\u7DCA\u8CBC\u97D3\u570B\u4E0A\
      \u67B6"
